name: C++ CI

on:
  push:
    branches:
      - main  # Bạn có thể thay đổi tên nhánh theo nhu cầu của bạn
  pull_request:
    branches:
      - main  # Bạn có thể thay đổi tên nhánh theo nhu cầu của bạn

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup C++ build tools
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'  # Bạn có thể chọn phiên bản Visual Studio cụ thể

      - name: Install CMake
        uses: lukka/get-cmake@v3
        with:
          cmake-version: '3.21.1'  # Thay đổi phiên bản CMake theo nhu cầu của bạn

      - name: Configure project
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest --test-dir build
