name: C++ CI on Windows

on: [push, pull_request]

jobs:
  build:
    # Chạy trên môi trường Windows
    runs-on: windows-latest

    strategy:
      matrix:
        compiler: [MSVC, gcc, clang]  # Chạy trên nhiều trình biên dịch

    steps:
    # Bước 1: Checkout repository
    - uses: actions/checkout@v2

    # Bước 2: Thiết lập môi trường tương ứng với trình biên dịch
    - name: Setup environment
      run: |
        if [ "${{ matrix.compiler }}" == "MSVC" ]; then
          echo "Setting up MSVC"
        elif [ "${{ matrix.compiler }}" == "gcc" ]; then
          choco install mingw
        elif [ "${{ matrix.compiler }}" == "clang" ]; then
          choco install llvm
        fi

    # Bước 3: Biên dịch mã nguồn với từng trình biên dịch
    - name: Build with ${{ matrix.compiler }}
      run: |
        if [ "${{ matrix.compiler }}" == "MSVC" ]; then
          cl /EHsc main.cpp  # Biên dịch bằng MSVC
        elif [ "${{ matrix.compiler }}" == "gcc" ]; then
          g++ -o my_program main.cpp  # Biên dịch bằng gcc
        elif [ "${{ matrix.compiler }}" == "clang" ]; then
          clang++ -o my_program main.cpp  # Biên dịch bằng clang
        fi

    # Bước 4: Chạy chương trình
    - name: Run program
      run: .\my_program.exe  # Chạy chương trình đã biên dịch
